### ISSUE TITLE
Not able to search

### ISSUE THREAD

**Issue by Daksh** [baddymaster/torrent-hound#1]
```
Dakshs-MacBook-Air:torrent-hound daksh$ bin/torrent-hound 
Enter search query : bull
Traceback (most recent call last):
  File "bin/torrent-hound", line 672, in <module>
    searchAllSites(query)
  File "bin/torrent-hound", line 638, in searchAllSites
    results_rarbg = searchRarbg(query)
  File "bin/torrent-hound", line 93, in searchRarbg
    response = requests.get(url, headers=headers)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 506, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='torrentapi.org', port=443): Max retries exceeded with url: /pubapi_v2.php?mode=search&search_string=bull&format=json_extended&ranked=0&token=None (Caused by SSLError(SSLError(1, u'[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)'),))

```

**Comment by Daksh** [comment]
Fixed it with 

> pip install --ignore-installed requests[security]
